name: GITHUB Actions Exercise
run-name: ${{GITHUB.actor}} is testing our branch
on: [push]
jobs:
  exploregithub:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "This is the first message in logs"
      
      - name: Second step
        run: echo "THis is second message in logs"
      
      
