name: Main Pipeline

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
